image: Visual Studio 2019

version: 0.0.{build}-{branch}

pull_requests:
  do_not_increment_build_number: true

install:
  - choco install bazel

before_build:
  - ps: New-Item -ItemType File -Path WORKSPACE

build_script:
  - ps: bazel build //EncounterRoller

after_build:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  - ps: 7z a EncounterRoller.zip %APPVEYOR_BUILD_FOLDER%\bazel-bin/EncounterRoller/EncounterRoller.exe
  - ps: 7z a EncounterRoller.zip %APPVEYOR_BUILD_FOLDER%\bazel-bin/EncounterRoller/EncounterRoller.zip

artifacts:
  - path: EncounterRoller.zip
    name: Encounter Roller