py_library(
    name = "settings_manager_lib",
    srcs = [
        "settings_manager.py",
    ],
    visibility = ["//visibility:public"],
    deps = [
    ],
)

py_library(
    name = "table_manager_lib",
    srcs = [
        "table_manager.py",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//EncounterRoller/lib:template_json_lib"
    ],
)

py_library(
    name = "xp_lib",
    srcs = [
        "xp.py",
    ],
    visibility = ["//visibility:public"],
    deps = [
    ],
)

py_library(
    name = "template_json_lib",
    srcs = [
        "template_json.py",
    ],
    visibility = ["//visibility:public"],
    deps = [
    ],
)